#!/bin/bash

WEBDIR=/var/www/cookbook.andygoetz.org/public_html
COOKBOOKREPO=/home/agoetz/cookbook.git
RECIPEREPO=/var/www/cookbook.andygoetz.org/public_html/repos
RECIPEDIR=$(mktemp -d)
COOKBOOKDIR=$(mktemp -d)

echo 'cloning the repo...'
git clone $COOKBOOKREPO $COOKBOOKDIR 
echo "CDing to $COOKBOOKDIR ..."
pushd $COOKBOOKDIR



echo "Generating the website..."
./gencookbook.py -o $WEBDIR -r $RECIPEREPO -s style.css 
echo "returning..."
popd

echo "cleaning up the temporary repo"
rm -rf $COOKBOOKDIR
