#!/bin/bash

WEBDIR=/var/www/cookbook.andygoetz.org/public_html
COOKBOOKREPO=/home/agoetz/cookbook.git
RECIPEREPO=/home/agoetz/recipes
RECIPEDIR=$(mktemp -d)
COOKBOOKDIR=$(mktemp -d)

echo 'cloning the repos...'
git clone $RECIPEREPO $RECIPEDIR
git clone $COOKBOOKREPO $COOKBOOKDIR 
echo "CDing to $COOKBOOKDIR ..."
pushd $COOKBOOKDIR



echo "Generating the website..."
./gencookbook.py -o $WEBDIR -r $RECIPEDIR -s style.css 

echo "returning..."
popd

echo "cleaning up the temporary repo"
rm -rf $RECIPEDIR
rm -rf $COOKBOOKDIR
